### ISSUE TITLE
wsl上での実行ができない

### ISSUE THREAD

**Issue by DENGEKI-TDU** [DENGEKI-TDU/dengeki-discord-bot#1]
- WSL上で実行をすると、以下のエラーによりデータベースに接続ができない(以下は例として/absentを使用)
<details>
Traceback (most recent call last):
  File "/home/kimshun/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore  
  File "/mnt/c/Users/sicp3/OneDrive - 東京電機大学/デスクトップ/演劇部(DENGEKI)/discord_bot/dengeki-discord-bot/main.py", line 35, in absent    
    absent_list_append(interaction.user.mention,mode,date,dt_now,memo)  
  File "/mnt/c/Users/sicp3/OneDrive - 東京電機大学/デスクトップ/演劇部(DENGEKI)/discord_bot/dengeki-discord-bot/absent.py", line 11, in absent_list_append
    connection = psycopg2.connect(host=DB_HOST,
  File "/home/kimshun/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

The above exception was the direct cause of the following exception:    

Traceback (most recent call last):
  File "/home/kimshun/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)        
  File "/home/kimshun/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/kimshun/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'absent' raised an exception: OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
</details>

**Comment by kimshun0213kr** [comment]
WSL上で実行する必要はないためclose
